services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      #MYSQL_DATABASE: bustravel
      #MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bustravel
  
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://host.docker.internal:3306/bustravel
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
    command: start-dev
    ports:
      - "8080:8080"

volumes:
  mysql_data:
    driver: local

networks:
  bustravel:
    driver: bridge
    external: true
    name: bustravel